services:
  - type: web
    name: metabase
    plan: free  # 512MB RAM, 0.1 CPU
    envVars:
      - key: MB_JETTY_PORT
        value: "3000"
      - key: MB_JETTY_HOST
        value: "0.0.0.0"
      - key: JAVA_OPTS
        value: "-Xmx350m -Xms128m -XX:+UseSerialGC"
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant  # Your ElephantSQL database name
          property: connectionString
      - key: MB_DISABLE_SCHEDULER
        value: "true"
      - key: MB_DISABLE_METRICS
        value: "true"
    healthCheckPath: /api/health
    initialDelaySec: 180  # Give Metabase 3 mins to start
