services:
  - type: web
    name: metabase
    plan: free
    port: 3000  
    envVars:
      - key: MB_JETTY_PORT
        value: "3000"
      - key: MB_JETTY_HOST
        value: "0.0.0.0"
      - key: JAVA_OPTS
        value: "-Xmx250m -Xms64m -XX:+UseSerialGC -XX:MaxRAM=400m" 
      - key: MB_DB_TYPE 
        value: "postgres"
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant
          property: connectionString
      - key: MB_DB_CONNECTION_TIMEOUT_MS 
        value: "5000"
      - key: MB_DISABLE_SCHEDULER
        value: "true"
      - key: MB_DISABLE_METRICS
        value: "true"
      - key: MB_JETTY_MAX_THREADS  
        value: "5"
    healthCheckPath: /api/health
    initialDelaySec: 180
